import 'package:secure_access/core/base_classes/base_repository.dart';
import 'package:secure_access_repository/models/secure_access_visitations_vehicle_model/secure_access_visitations_vehicle_model.dart';

abstract class ManualVehicleContinueClickedRepository  extends BaseRepository<ManualVehicleContinueClickedRepositoryParams, String>{}

class ManualVehicleContinueClickedRepositoryParams extends BaseRepositoryParams{

  final SecureAccessVisitationsVehicleModel manualVehicleContinueClickedModel;

  ManualVehicleContinueClickedRepositoryParams({required this.manualVehicleContinueClickedModel});
}
