name: secure_access
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl_utils: ^2.8.7
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  injectable: ^2.4.2
  circle_nav_bar: ^2.1.0+1
  flutter_flavor: ^3.1.3
  dio: ^5.7.0
  logger: ^2.4.0
  dropdown_textfield: ^1.2.0
  flutter_calendar_carousel: ^2.4.3
  equatable: ^2.0.5
  firebase_core: ^3.4.0
  local_auth: ^2.3.0
  intl_phone_field: ^3.2.0
  dropdown_search: ^5.0.6
  firebase_database: ^11.1.1
  get: ^4.6.6
  open_filex: ^4.5.0
  encrypt: ^5.0.3
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.10+1
  heroicons: ^0.10.0
  flutter_flavorizr: ^2.2.3
  firebase_auth: ^5.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.6.1
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9


flutter:

  uses-material-design: true

  assets:

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_local: en
  arb_dir: lib/localization
  output_dir: lib/generated