import 'package:secure_access/core/base_classes/base_repository.dart';
import 'package:secure_access_repository/models/secure_access_visitation_model/secure_access_visitations_model.dart';

abstract class PersonDetailsContinueClickedRepository  extends BaseRepository<PersonDetailsContinueClickedRepositoryParams, String>{}

class PersonDetailsContinueClickedRepositoryParams extends BaseRepositoryParams{

  PersonDetailsContinueClickedRepositoryParams({required this.personDetailsContinueClickedModel});
  final SecureAccessVisitationsModel personDetailsContinueClickedModel;
}
