// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhGU9Oah2pd9oXYLdMgpe-bZJoUxaComk',
    appId: '1:850404688205:android:61b454326165c29947f704',
    messagingSenderId: '850404688205',
    projectId: 'safe-access-499b9',
    databaseURL: 'https://safe-access-499b9-default-rtdb.firebaseio.com',
    storageBucket: 'safe-access-499b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0DJKzt_Q4vSZgW7Imk4qUbsX6aeSkG8',
    appId: '1:850404688205:ios:c391b4477b11955147f704',
    messagingSenderId: '850404688205',
    projectId: 'safe-access-499b9',
    databaseURL: 'https://safe-access-499b9-default-rtdb.firebaseio.com',
    storageBucket: 'safe-access-499b9.firebasestorage.app',
    iosBundleId: 'progressive.app.secureAccess',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKcKUvJlWyxajSJ5nFURbgqPyHd3iBIAc',
    appId: '1:850404688205:web:9c6c46804faf546547f704',
    messagingSenderId: '850404688205',
    projectId: 'safe-access-499b9',
    authDomain: 'safe-access-499b9.firebaseapp.com',
    databaseURL: 'https://safe-access-499b9-default-rtdb.firebaseio.com',
    storageBucket: 'safe-access-499b9.firebasestorage.app',
    measurementId: 'G-FY6GG2XEQY',
  );

}